args <- commandArgs()
data<-read.csv(args[4],header=TRUE,sep="\t")
png(filename = paste(args[4],".png",sep=""), width = 1180, height = 1180, units = "px", pointsize = 20, bg = "white", res = NA)
plot(data$Position,data$Mean.Cov,type="l",xlab="Position relative to TSS",ylab="Read depth")
polygon(c(data$Position,rev(data$Position)),c(data$LowerBound,rev(data$UpperBound)),col = "grey75", border = FALSE)
lines(data$Position,data$Mean.Cov)
dev.off()
png(filename = paste(args[4],".ylim_0.png",sep=""), width = 1180, height = 1180, units = "px", pointsize = 20, bg = "white", res = NA)
plot(data$Position,data$Mean.Cov,type="l",ylim=c(0,max(data$Mean.Cov)+5),xlab="Position relative to TSS",ylab="Read depth")
polygon(c(data$Position,rev(data$Position)),c(data$LowerBound,rev(data$UpperBound)),col = "grey75", border = FALSE)
lines(data$Position,data$Mean.Cov)
dev.off()
